# ModSlut per-user preferences. Safe to edit while ModSlut is closed.
default_game=auto
font_size=16
panel=552
pos=178,77
settings_pos=158,20
settings_size=846x840
size=1618x1058
theme=Black Hand   Sithis
user_rules_only=0
